/**
 * Tiptap HTML parsing utilities
 * Extracts embed information from HTML generated by Admin Panel
 */

export interface VideoEmbedData {
  type: 'video'
  src: string
  width?: number
  height?: number
  controls?: boolean
  autoplay?: boolean
  loop?: boolean
}

export interface SocialMediaEmbedData {
  type: 'socialMedia'
  src: string
  platform: 'youtube' | 'facebook' | 'instagram' | 'tiktok' | 'linkedin' | 'pinterest' | 'x'
  width?: number
}

export type EmbedData = VideoEmbedData | SocialMediaEmbedData

/**
 * Parse video embed data from HTML element
 */
export function parseVideoEmbed(element: HTMLElement): VideoEmbedData | null {
  if (!element.hasAttribute('data-video-embed')) {
    return null
  }

  return {
    type: 'video',
    src: element.getAttribute('data-src') || '',
    width: element.getAttribute('data-width')
      ? parseInt(element.getAttribute('data-width')!, 10)
      : undefined,
    height: element.getAttribute('data-height')
      ? parseInt(element.getAttribute('data-height')!, 10)
      : undefined,
    controls: element.getAttribute('data-controls') !== 'false',
    autoplay: element.getAttribute('data-autoplay') === 'true',
    loop: element.getAttribute('data-loop') === 'true',
  }
}

/**
 * Parse social media embed data from HTML element
 */
export function parseSocialMediaEmbed(element: HTMLElement): SocialMediaEmbedData | null {
  if (!element.hasAttribute('data-social-media-embed')) {
    return null
  }

  const platform = element.getAttribute('data-platform') as SocialMediaEmbedData['platform']

  return {
    type: 'socialMedia',
    src: element.getAttribute('data-src') || '',
    platform: platform || 'youtube',
    width: element.getAttribute('data-width')
      ? parseInt(element.getAttribute('data-width')!, 10)
      : undefined,
  }
}

/**
 * Extract all embeds from HTML string
 */
export function extractEmbeds(html: string): {
  htmlWithoutEmbeds: string
  embeds: Array<{ index: number; data: EmbedData }>
} {
  // Guard: Only run on client-side (DOMParser and document are browser-only APIs)
  if (typeof window === 'undefined') {
    return {
      htmlWithoutEmbeds: html,
      embeds: []
    }
  }

  const parser = new DOMParser()
  const doc = parser.parseFromString(html, 'text/html')
  const embeds: Array<{ index: number; data: EmbedData }> = []
  const placeholders: string[] = []

  // Process all div elements to find embeds
  const divs = doc.querySelectorAll('div[data-video-embed], div[data-social-media-embed]')

  divs.forEach((div, index) => {
    const videoEmbed = parseVideoEmbed(div as HTMLElement)
    const socialEmbed = parseSocialMediaEmbed(div as HTMLElement)

    if (videoEmbed) {
      embeds.push({ index, data: videoEmbed })
      placeholders.push(`__EMBED_PLACEHOLDER_${index}__`)
      div.replaceWith(document.createTextNode(placeholders[index]))
    } else if (socialEmbed) {
      embeds.push({ index, data: socialEmbed })
      placeholders.push(`__EMBED_PLACEHOLDER_${index}__`)
      div.replaceWith(document.createTextNode(placeholders[index]))
    }
  })

  return {
    htmlWithoutEmbeds: doc.body.innerHTML,
    embeds,
  }
}

/**
 * Check if a URL is a valid video file URL
 */
export function isValidVideoUrl(url: string): boolean {
  if (!url) return false

  const videoExtensions = ['.mp4', '.webm', '.ogg', '.mov', '.avi', '.wmv']
  const lowerUrl = url.toLowerCase()

  return (
    videoExtensions.some((ext) => lowerUrl.endsWith(ext)) ||
    lowerUrl.includes('video/') ||
    url.startsWith('blob:')
  )
}
